name: Deploy Backend to Container
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Backend to Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      # Tests uitgeschakeld - voeg toe als je tests hebt
      # - name: Run tests
      #   run: npm test
      
      # Voor Express.js meestal geen build step nodig
      # - name: Build backend
      #   run: npm run build
      
      - name: Upload backend to VM
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "/root/api"
          strip_components: 1
      
      - name: Deploy Backend to Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Ga naar backend directory en install dependencies
            docker exec nextjs-app-fixed sh -c "cd /api && npm install --omit=dev"
            
            # Kill any existing screen sessions for backend
            docker exec nextjs-app-fixed screen -X -S backend quit || true
            
            # Start new screen session with Express server (poort 3001)
            docker exec -d nextjs-app-fixed screen -dmS backend sh -c "cd /api && PORT=3001 npm run server"
